# Generated by Django 6.0 on 2025-12-11 07:41

import abdm.models.consent
import care.utils.models.validators
import django.contrib.postgres.fields
import django.core.validators
import django.db.migrations.operations.special
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('abdm', '0001_initial_squashed_0007_alter_abhanumber_id'), ('abdm', '0008_abhanumber_new'), ('abdm', '0009_healthfacility'), ('abdm', '0010_healthfacility_registered'), ('abdm', '0011_alter_abhanumber_abha_number_and_more'), ('abdm', '0012_consentrequest_status'), ('abdm', '0013_abhanumber_patient'), ('abdm', '0014_abhanumber_mobile'), ('abdm', '0015_remove_abhanumber_txn_id_transaction'), ('abdm', '0016_rename_patient_abhanumber_deprecated_patient'), ('abdm', '0017_abhanumber_patient'), ('abdm', '0018_alter_consentartefact_hi_types_and_more'), ('abdm', '0016_transaction_status_alter_consentartefact_hi_types_and_more'), ('abdm', '0019_merge_20250526_1551'), ('abdm', '0017_add_file_upload_care_context_transactions'), ('abdm', '0020_merge_20250620_1504'), ('abdm', '0021_remove_abhanumber_deprecated_patient'), ('abdm', '0022_consentartefact_encounter_consentrequest_encounter'), ('abdm', '0023_create_patient_identifiers_for_existing_abha')]

    initial = True

    dependencies = [
        ('emr', '0001_initial'),
        ('emr', '0040_alter_observation_interpretation'),
        ('facility', '0378_consultationbedasset_consultationbed_assets'),
        ('facility', '0432_alter_fileupload_file_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('hf_id', models.CharField(max_length=50, unique=True)),
                ('facility', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='facility.facility', to_field='external_id')),
                ('registered', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AbhaNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('abha_number', models.TextField(blank=True, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('first_name', models.TextField(blank=True, null=True)),
                ('health_id', models.TextField(blank=True, null=True, unique=True)),
                ('last_name', models.TextField(blank=True, null=True)),
                ('middle_name', models.TextField(blank=True, null=True)),
                ('profile_photo', models.TextField(blank=True, null=True)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('date_of_birth', models.TextField(blank=True, null=True)),
                ('district', models.TextField(blank=True, null=True)),
                ('gender', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('pincode', models.TextField(blank=True, null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('new', models.BooleanField(default=False)),
                ('deprecated_patient', models.BigIntegerField(blank=True, null=True)),
                # ('deprecated_patient', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='abha_number', to='facility.patientregistration')),
                ('mobile', models.TextField(blank=True, null=True)),
                ('patient', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='abha_number', to='emr.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConsentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('consent_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('care_contexts', models.JSONField(default=list, validators=[care.utils.models.validators.JSONFieldSchemaValidator({'$schema': 'http://json-schema.org/draft-07/schema#', 'content': [{'additionalProperties': False, 'properties': {'careContextReference': {'type': 'string'}, 'patientReference': {'type': 'string'}}, 'required': ['patientReference', 'careContextReference'], 'type': 'object'}], 'type': 'array'})])),
                ('purpose', models.CharField(choices=[('CAREMGT', 'Care Management'), ('BTG', 'Break The Glass'), ('PUBHLTH', 'Public Health'), ('HPAYMT', 'Healthcare Payment'), ('DSRCH', 'Disease Specific Healthcare Research'), ('PATRQT', 'Self Requested')], default='CAREMGT', max_length=20)),
                ('hi_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Prescription', 'Prescription'), ('DiagnosticReport', 'Diagnostic Report'), ('OPConsultation', 'Op Consultation'), ('DischargeSummary', 'Discharge Summary'), ('ImmunizationRecord', 'Immunization Record'), ('HealthDocumentRecord', 'Record Artifact'), ('WellnessRecord', 'Wellness Record'), ('Invoice', 'Invoice')], max_length=20), default=list)),
                ('hip', models.CharField(blank=True, max_length=50, null=True)),
                ('hiu', models.CharField(blank=True, max_length=50, null=True)),
                ('access_mode', models.CharField(choices=[('VIEW', 'View'), ('STORE', 'Store'), ('QUERY', 'Query'), ('STREAM', 'Stream')], default='VIEW', max_length=20)),
                ('from_time', models.DateTimeField(blank=True, default=abdm.models.consent.Consent.default_from_time, null=True)),
                ('to_time', models.DateTimeField(blank=True, default=abdm.models.consent.Consent.default_to_time, null=True)),
                ('expiry', models.DateTimeField(blank=True, default=abdm.models.consent.Consent.default_expiry, null=True)),
                ('frequency_unit', models.CharField(choices=[('HOUR', 'Hour'), ('DAY', 'Day'), ('WEEK', 'Week'), ('MONTH', 'Month'), ('YEAR', 'Year')], default='HOUR', max_length=20)),
                ('frequency_value', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('frequency_repeats', models.PositiveSmallIntegerField(default=0)),
                ('patient_abha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abdm.abhanumber', to_field='health_id')),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('GRANTED', 'Granted'), ('DENIED', 'Denied'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], default='REQUESTED', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('reference_id', models.CharField(max_length=100)),
                ('type', models.SmallIntegerField(choices=[(1, 'Create Or Link Abha Number'), (2, 'Create Abha Address'), (3, 'Scan And Share'), (4, 'Link Care Context'), (5, 'Exchange Data'), (6, 'Access Data')])),
                ('meta_data', models.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('status', models.SmallIntegerField(choices=[(1, 'Initiated'), (2, 'Completed'), (3, 'Failed'), (4, 'Cancelled')], default=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConsentArtefact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('consent_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('care_contexts', models.JSONField(default=list, validators=[care.utils.models.validators.JSONFieldSchemaValidator({'$schema': 'http://json-schema.org/draft-07/schema#', 'content': [{'additionalProperties': False, 'properties': {'careContextReference': {'type': 'string'}, 'patientReference': {'type': 'string'}}, 'required': ['patientReference', 'careContextReference'], 'type': 'object'}], 'type': 'array'})])),
                ('purpose', models.CharField(choices=[('CAREMGT', 'Care Management'), ('BTG', 'Break The Glass'), ('PUBHLTH', 'Public Health'), ('HPAYMT', 'Healthcare Payment'), ('DSRCH', 'Disease Specific Healthcare Research'), ('PATRQT', 'Self Requested')], default='CAREMGT', max_length=20)),
                ('hi_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Prescription', 'Prescription'), ('DiagnosticReport', 'Diagnostic Report'), ('OPConsultation', 'Op Consultation'), ('DischargeSummary', 'Discharge Summary'), ('ImmunizationRecord', 'Immunization Record'), ('HealthDocumentRecord', 'Record Artifact'), ('WellnessRecord', 'Wellness Record'), ('Invoice', 'Invoice')], max_length=20), default=list)),
                ('hip', models.CharField(blank=True, max_length=50, null=True)),
                ('hiu', models.CharField(blank=True, max_length=50, null=True)),
                ('access_mode', models.CharField(choices=[('VIEW', 'View'), ('STORE', 'Store'), ('QUERY', 'Query'), ('STREAM', 'Stream')], default='VIEW', max_length=20)),
                ('from_time', models.DateTimeField(blank=True, default=abdm.models.consent.Consent.default_from_time, null=True)),
                ('to_time', models.DateTimeField(blank=True, default=abdm.models.consent.Consent.default_to_time, null=True)),
                ('expiry', models.DateTimeField(blank=True, default=abdm.models.consent.Consent.default_expiry, null=True)),
                ('frequency_unit', models.CharField(choices=[('HOUR', 'Hour'), ('DAY', 'Day'), ('WEEK', 'Week'), ('MONTH', 'Month'), ('YEAR', 'Year')], default='HOUR', max_length=20)),
                ('frequency_value', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('frequency_repeats', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('GRANTED', 'Granted'), ('DENIED', 'Denied'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], default='REQUESTED', max_length=20)),
                ('cm', models.CharField(blank=True, max_length=50, null=True)),
                ('key_material_algorithm', models.CharField(blank=True, default='ECDH', max_length=20, null=True)),
                ('key_material_curve', models.CharField(blank=True, default='Curve25519', max_length=20, null=True)),
                ('key_material_public_key', models.CharField(blank=True, max_length=100, null=True)),
                ('key_material_private_key', models.CharField(blank=True, max_length=200, null=True)),
                ('key_material_nonce', models.CharField(blank=True, max_length=100, null=True)),
                ('signature', models.TextField(blank=True, null=True)),
                ('consent_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consent_artefacts', to='abdm.consentrequest', to_field='consent_id')),
                ('patient_abha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abdm.abhanumber', to_field='health_id')),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='abhanumber',
            name='deprecated_patient',
        ),
        migrations.AddField(
            model_name='consentartefact',
            name='encounter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='emr.encounter', to_field='external_id'),
        ),
        migrations.AddField(
            model_name='consentrequest',
            name='encounter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='emr.encounter', to_field='external_id'),
        ),
    ]
