# Generated by Django 6.0 on 2026-08-06 15:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abdm', '0001_initial_squashed'),
        ('emr', '0080_alter_activitydefinition_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'Create Or Link Abha Number'), (2, 'Create Abha Address'), (3, 'Scan And Share'), (4, 'Link Care Context'), (5, 'Exchange Data'), (6, 'Access Data'), (7, 'Scan And Pay')]),
        ),
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('open_order_request_id', models.UUIDField(db_index=True, unique=True)),
                ('status', models.CharField(choices=[('OPEN_ORDER_SHARED', 'Open Order Shared'), ('PAYMENT_INITIATED', 'Payment Initiated'), ('SUCCESS', 'Success'), ('CANCELED', 'Canceled'), ('PENDING', 'Pending'), ('FAIL', 'Fail'), ('REFUND_INITIATED', 'Refund Initiated'), ('REFUND_SUCCESS', 'Refund Success')], default='OPEN_ORDER_SHARED', max_length=50)),
                ('order_number', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('payment_link_id', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('abha_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abdm.abhanumber')),
                ('health_facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abdm.healthfacility')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='emr.invoice')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
