# Generated by Django 6.0 on 2026-08-06 01:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abdm', '0001_initial_squashed'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundCallback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('callback_type', models.CharField(choices=[('token__on_generate_token', 'hip/token/on-generate-token'), ('link__on_carecontext', 'link/on_carecontext'), ('patient__care_context__discover', 'hip/patient/care-context/discover'), ('link__care_context__init', 'hip/link/care-context/init'), ('link__care_context__confirm', 'hip/link/care-context/confirm'), ('consent__request__hip__notify', 'consent/request/hip/notify'), ('health_information__request', 'hip/health-information/request'), ('patient__share', 'hip/patient/share'), ('consent__request__on_init', 'hiu/consent/request/on-init'), ('consent__request__on_status', 'hiu/consent/request/on-status'), ('consent__request__notify', 'hiu/consent/request/notify'), ('consent__on_fetch', 'hiu/consent/on-fetch'), ('health_information__on_request', 'hiu/health-information/on-request'), ('health_information__transfer', 'hiu/health-information/transfer')], db_index=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['callback_type', 'request_id'], name='abdm_inboun_callbac_bcb42c_idx'), models.Index(fields=['status', 'callback_type'], name='abdm_inboun_status_dfe472_idx')],
            },
        ),
    ]
