# Generated by Django 6.0 on 2026-08-06 15:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abdm', '0002_inboundcallback'),
        ('emr', '0080_alter_activitydefinition_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'Create Or Link Abha Number'), (2, 'Create Abha Address'), (3, 'Scan And Share'), (4, 'Link Care Context'), (5, 'Exchange Data'), (6, 'Access Data'), (7, 'Scan And Pay')]),
        ),
        migrations.AlterField(
            model_name='inboundcallback',
            name='callback_type',
            field=models.CharField(choices=[('token__on_generate_token', 'hip/token/on-generate-token'), ('link__on_carecontext', 'link/on_carecontext'), ('patient__care_context__discover', 'hip/patient/care-context/discover'), ('link__care_context__init', 'hip/link/care-context/init'), ('link__care_context__confirm', 'hip/link/care-context/confirm'), ('consent__request__hip__notify', 'consent/request/hip/notify'), ('health_information__request', 'hip/health-information/request'), ('patient__share', 'hip/patient/share'), ('consent__request__on_init', 'hiu/consent/request/on-init'), ('consent__request__on_status', 'hiu/consent/request/on-status'), ('consent__request__notify', 'hiu/consent/request/notify'), ('consent__on_fetch', 'hiu/consent/on-fetch'), ('health_information__on_request', 'hiu/health-information/on-request'), ('health_information__transfer', 'hiu/health-information/transfer'), ('patient__share__open_order', 'patient/share/open-order'), ('patient__selection', 'patient/selection'), ('patient__scan_pay__on_notify', 'patient/scan-pay/on-notify'), ('patient__scan_pay__order_status', 'patient/scan-pay/order-status')], db_index=True, max_length=64),
        ),
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('open_order_request_id', models.UUIDField(db_index=True, unique=True)),
                ('status', models.CharField(choices=[('OPEN_ORDER_SHARED', 'Open Order Shared'), ('PAYMENT_INITIATED', 'Payment Initiated'), ('SUCCESS', 'Success'), ('CANCELED', 'Canceled'), ('PENDING', 'Pending'), ('FAIL', 'Fail'), ('REFUND_INITIATED', 'Refund Initiated'), ('REFUND_SUCCESS', 'Refund Success')], default='OPEN_ORDER_SHARED', max_length=50)),
                ('order_number', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('payment_link_id', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('abha_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abdm.abhanumber')),
                ('health_facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abdm.healthfacility')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='emr.invoice')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
