# Generated by Django 6.0 on 2026-08-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abdm', '0003_alter_transaction_type_paymentorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentorder',
            name='payment_link_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
