# Generated by Django 6.0 on 2026-09-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abdm', '0005_paymentorder_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorder',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
    ]
