# Generated by Django 6.0 on 2026-09-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abdm', '0006_paymentorder_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorder',
            name='abha_address',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
