# Generated by Django 5.1.4 on 2025-06-16 00:47


from uuid import uuid4

from abdm.models.base import HealthInformationType
from abdm.models.transaction import TransactionStatus, TransactionType
from django.core.paginator import Paginator
from django.db import migrations
from django.db.models import Q


def create_transactions_for_file_upload_care_contexts(apps, schema_editor):
    AbhaNumber = apps.get_model("abdm", "AbhaNumber")
    Transaction = apps.get_model("abdm", "Transaction")
    User = apps.get_model("users", "User")
    FileUpload = apps.get_model("facility", "FileUpload")

    paginator = Paginator(
        AbhaNumber.objects.filter().select_related("patient").order_by("id"),
        1000,
    )
    for page_num in paginator.page_range:
        bulk_create_data = []
        for abha_number in paginator.get_page(page_num):
            if not abha_number.patient:
                continue

            hf_care_contexts = {}
            for consultation in abha_number.patient.consultations.all():
                consultation_care_contexts = []

                files = FileUpload.objects.filter(
                    Q(associating_id=consultation.external_id)
                    | Q(associating_id=consultation.id),
                    file_type=2, # FileUpload.FileType.CONSULTATION
                    upload_completed=True,
                )
                for file in files:
                    consultation_care_contexts.append(
                        {
                            "reference": f"v1::file_upload::{file.external_id}",
                            "display": f"File Uploaded on {file.created_date.date()}",
                            "hi_type": HealthInformationType.RECORD_ARTIFACT,
                        }
                    )

                facility = consultation.facility
                if not hasattr(facility, "healthfacility"):
                    continue

                hf_id = facility.healthfacility.hf_id
                if hf_id in hf_care_contexts:
                    hf_care_contexts[hf_id].extend(consultation_care_contexts)
                else:
                    hf_care_contexts[hf_id] = consultation_care_contexts

            for hf_id in hf_care_contexts:
                care_contexts = hf_care_contexts[hf_id]

                if len(care_contexts) == 0:
                    continue

                transaction = Transaction(
                    reference_id=uuid4(),
                    type=TransactionType.LINK_CARE_CONTEXT,
                    status=TransactionStatus.FAILED,
                    meta_data={
                        "abha_number": str(abha_number.external_id),
                        "type": "hip_initiated_linking",
                        "care_contexts": list(map(lambda x: x["reference"], care_contexts)),
                        "hf_id": hf_id,
                    },
                    created_by=User.objects.filter(is_superuser=True).first(),
                )
                bulk_create_data.append(transaction)

        Transaction.objects.bulk_create(bulk_create_data)





class Migration(migrations.Migration):

    dependencies = [
        ('abdm', '0016_transaction_status_alter_consentartefact_hi_types_and_more'),
    ]

    operations = [
        migrations.RunPython(
            code=create_transactions_for_file_upload_care_contexts,
            reverse_code=migrations.RunPython.noop,
        )
    ]
