# Generated by Django 5.1.4 on 2025-05-26 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abdm', '0016_transaction_status_alter_consentartefact_hi_types_and_more'),
        ('abdm', '0018_alter_consentartefact_hi_types_and_more'),
    ]

    operations = [
    ]
