# Generated by Django 5.1.4 on 2025-03-06 06:22

from django.core.paginator import Paginator
from django.db import migrations
from django.db.models import Q

def migrate_patient_reference(apps, schema_editor):
    AbhaNumber = apps.get_model("abdm", "AbhaNumber")

    abha_numbers = AbhaNumber.objects.filter(Q(deprecated_patient__isnull=False)).only("deprecated_patient").order_by("id")
    paginator = Paginator(abha_numbers, 1000)
    for page_number in paginator.page_range:
        bulk = []
        for abha_number in paginator.page(page_number).object_list:
            abha_number.patient_id = abha_number.deprecated_patient.migrated_emr_patient_id
            bulk.append(abha_number)

        AbhaNumber.objects.bulk_update(bulk, ["patient"])

class Migration(migrations.Migration):

    dependencies = [
        ('abdm', '0018_alter_consentartefact_hi_types_and_more'),
        ('facility', '0491_migrate_consent_records'),
    ]

    operations = [
        migrations.RunPython(migrate_patient_reference, migrations.RunPython.noop),
        migrations.RemoveField(model_name="abhanumber", name="deprecated_patient"),
    ]
