# Generated by Django 5.1.4 on 2025-03-06 06:23

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('abdm', '0019_data_migration'),
    ]

    operations = [
        migrations.RemoveField(model_name="abhanumber", name="deprecated_patient"),
    ]