# Generated by Django 5.1.4 on 2025-06-20 09:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('abdm', '0017_add_file_upload_care_context_transactions'),
        ('abdm', '0019_merge_20250526_1551'),
    ]

    operations = [
    ]
