# Generated by Django 5.1.4 on 2025-09-15 18:34

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [
        ('abdm', '0020_remove_abhanumber_deprecated_patient'),
    ]

    dependencies = [
        ('abdm', '0020_merge_20250620_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abhanumber',
            name='deprecated_patient',
        ),
    ]
