# Generated by Django 5.1.4 on 2025-07-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abdm', '0020_merge_20250620_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='abhanumber',
            name='phr_auto_approve_request_id',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='abhanumber',
            name='phr_health_id',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
