# Generated by Django 5.1.4 on 2025-05-26 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abdm', '0019_merge_20250526_1551'),
        ('abdm', '0020_remove_abhanumber_deprecated_patient'),
    ]

    operations = [
    ]
