# Generated by Django 5.1.4 on 2025-08-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abdm', '0021_abhanumber_phr_auto_approve_request_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abhanumber',
            name='district_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abhanumber',
            name='state_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
