# Generated by Django 5.1.14 on 2025-11-17 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abdm', '0021_remove_abhanumber_deprecated_patient'),
        ('emr', '0040_alter_observation_interpretation'),
    ]

    operations = [
        migrations.AddField(
            model_name='consentartefact',
            name='encounter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='emr.encounter', to_field='external_id'),
        ),
        migrations.AddField(
            model_name='consentrequest',
            name='encounter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='emr.encounter', to_field='external_id'),
        ),
    ]
