# Generated by Django 5.1.4 on 2025-06-23 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abdm', '0020_merge_20250620_1504'),
        ('abdm', '0021_merge_20250526_1613'),
    ]

    operations = [
    ]
