# Generated by Django 5.1.4 on 2025-08-20 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abdm', '0022_abhanumber_district_code_abhanumber_state_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abhanumber',
            name='phr_auto_approve_request_id',
        ),
        migrations.AddField(
            model_name='abhanumber',
            name='phr_health_ids_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
