# Generated by Django 5.1.4 on 2025-07-22 14:19

from uuid import uuid4

from abdm.models.transaction import TransactionStatus, TransactionType
from abdm.service.helper import generate_care_contexts_for_existing_data
from django.core.paginator import Paginator
from django.db import migrations


def create_v2_care_contexts(apps, schema_editor):
    AbhaNumber = apps.get_model("abdm", "AbhaNumber")
    Transaction = apps.get_model("abdm", "Transaction")
    User = apps.get_model("users", "User")

    care_context_set = set()
    for tx in Transaction.objects.filter(type=TransactionType.LINK_CARE_CONTEXT).iterator():
        care_contexts = tx.meta_data.get("care_contexts", [])
        care_context_set.update(care_contexts)

    paginator = Paginator(
        AbhaNumber.objects.filter().select_related("patient").order_by("id"),
        1000,
    )
    for page_num in paginator.page_range:
        bulk_create_data = []
        for abha_number in paginator.get_page(page_num):
            if not abha_number.patient:
                continue

            hf_care_contexts = generate_care_contexts_for_existing_data(abha_number.patient)

            for hf_id in hf_care_contexts:
                care_contexts = hf_care_contexts[hf_id]

                filtered_care_contexts = list(filter(lambda care_context: care_context.get("reference") not in care_context_set, care_contexts))

                if len(filtered_care_contexts) == 0:
                    continue


                transaction = Transaction(
                    reference_id=uuid4(),
                    type=TransactionType.LINK_CARE_CONTEXT,
                    status=TransactionStatus.FAILED,
                    meta_data={
                        "abha_number": str(abha_number.external_id),
                        "type": "hip_initiated_linking",
                        "care_contexts": list(map(lambda x: x["reference"], filtered_care_contexts)),
                        "hf_id": hf_id,
                    },
                    created_by=User.objects.filter(is_superuser=True).first(),
                )
                bulk_create_data.append(transaction)

        Transaction.objects.bulk_create(bulk_create_data)



class Migration(migrations.Migration):

    dependencies = [
        ('abdm', '0022_merge_20250623_2335'),
    ]

    operations = [
        migrations.RunPython(
            code=create_v2_care_contexts,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
