# Generated by Django 5.1.4 on 2025-07-07 07:44

from care_abdm.abdm.utils.user import get_or_create_abdm_user
from django.db import migrations
from django.core.paginator import Paginator
from django.db.models import Q
from abdm.settings import plugin_settings


def create_patient_identifiers_for_existing_abha(apps, schema_editor):
    AbhaNumber = apps.get_model("abdm", "AbhaNumber")
    PatientIdentifier = apps.get_model("emr", "PatientIdentifier")
    PatientIdentifierConfig = apps.get_model("emr", "PatientIdentifierConfig")
    User = apps.get_model("users", "User")

    abdm_user = get_or_create_abdm_user()
    patient_identifier_config, _ = PatientIdentifierConfig.objects.get_or_create(
        config__system=plugin_settings.ABHA_NUMBER_IDENTIFIER_SYSTEM.get("system"),
        facility=None,
        created_by=abdm_user,
        defaults={
            "status": "active",
            "config": {
                "use": "official",
                "description": plugin_settings.ABHA_NUMBER_IDENTIFIER_SYSTEM.get("display"),
                "required": False,
                "unique": True,
                "regex": "",
                "system": plugin_settings.ABHA_NUMBER_IDENTIFIER_SYSTEM.get("system"),
                "display": plugin_settings.ABHA_NUMBER_IDENTIFIER_SYSTEM.get("display"),
                "retrieve_config": {
                    "retrieve_with_dob": False,
                    "retrieve_with_year_of_birth": False,
                    "retrieve_with_otp": False,
                },
            },
            "facility": None,
            "created_by": abdm_user,
        },
    )

    paginator = Paginator(
        AbhaNumber.objects.filter().select_related("patient").order_by("id"),
        1000,
    )
    for page_num in paginator.page_range:
        bulk_create_data = []
        for abha_number in paginator.get_page(page_num):
            if not abha_number.patient:
                continue

            patient_identifier = PatientIdentifier(
                patient=abha_number.patient,
                config=patient_identifier_config,
                value=abha_number.abha_number,
                created_by=abdm_user,
            )
            bulk_create_data.append(patient_identifier)

        PatientIdentifier.objects.bulk_create(bulk_create_data)

class Migration(migrations.Migration):

    dependencies = [
        ('abdm', '0022_consentartefact_encounter_consentrequest_encounter'),
    ]

    operations = [
        migrations.RunPython(
            code=create_patient_identifiers_for_existing_abha,
            reverse_code=migrations.RunPython.noop,
        )
    ]
