# Generated by Django 5.1.4 on 2025-08-23 00:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abdm', '0023_remove_abhanumber_phr_auto_approve_request_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhrNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('event_id', models.TextField(blank=True, null=True, unique=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('subscription_id', models.TextField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('abha_address', models.TextField(blank=True, null=True)),
                ('hip_id', models.TextField(blank=True, null=True)),
                ('contexts', models.JSONField(blank=True, default=list)),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('raw_event_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
