# Generated by Django 5.1.4 on 2025-08-31 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abdm', '0024_phrnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='consentartefact',
            name='patient_abha_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
