# Generated by Django 5.1.4 on 2025-11-07 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abdm', '0021_remove_abhanumber_deprecated_patient'),
        ('abdm', '0025_consentartefact_patient_abha_address'),
    ]

    operations = [
    ]
