# Generated by Django 5.1.4 on 2025-11-13 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abdm', '0026_merge_20251107_1515'),
        ('emr', '0039_formsubmission_questionnaireresponse_form_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='consentartefact',
            name='encounter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='emr.encounter', to_field='external_id'),
        ),
        migrations.AddField(
            model_name='consentrequest',
            name='encounter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='emr.encounter', to_field='external_id'),
        ),
    ]
